version: '3.7'
services:
    nginx_build:
        build:
            context: .
            dockerfile: nginx.docker
        depends_on:
            - npm_build
        ports:
            - "${WEBPORT_CLIENT}:80"
    npm_build:
        build:
            context: .
            dockerfile: npm.docker
        command: "bash -c 'npm run build && cp -arv /usr/src/app/dist/* /usr/src/app/html'"

        volumes:
            - ./html:/usr/src/app/html
