name: Test-CI-functions
on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v1
      - name: Cloning Kopnik-Server Repo in to the current container
        run: git clone https://github.com/kopnik-org/kopnik-server.git
      
      - name: Declaring envoirment variables
        env:
          DB_USER: db_user
          APP_ENV: test
          DB_PASWORD: db_password
          DB_NAME: db_name
          LOCAL_VIRTUAL_HOST: kopnik.org.local
          PRODUCTION_VIRTUAL_HOST: kopnik.org
          WEB_PORT: 8082
        run: make ./kopnik-server/test-full-up     
            


